image: ${CI_IMAGE}

before_script:
  - cp -r /root/citools .

stages:
  - build
  - publish

build:
  stage: build
  tags:
    - java
  script: yarn install && yarn build
  only:
    - tags

  artifacts:
    paths:
      - build/
    expire_in: 60 mins
    when: on_success

publish:
  stage: publish
  tags:
    - java
  script:
    - . ./citools/publish-image.sh
  only:
    - tags
