image: ${CI_IMAGE}

stages:
  - build
  - publish
  - deploy_staging

build:
  stage: build
  retry: 2
  tags:
    - java
  script:
    - yarn config set registry https://registry.npm.taobao.org
    - yarn config list
    - yarn install
    - NODE_ENV=production yarn build # do not set this env var to variables because yarn install wont install dev packages
  only:
    - tags
    - dev
    - test
  artifacts:
    paths:
      - build/
    expire_in: 60 mins
    when: on_success

publish:
  stage: publish
  retry: 2
  tags:
    - java
  script:
    - cp -r /root/citools .
    - . ./citools/publish-image.sh
  only:
    - tags
    - dev
    - test
deploy_staging:
  stage: deploy_staging
  image: ${DEPLOY_IMAGE}
  retry: 2
  tags:
    - java
  dependencies: []
  variables:
    ENVIRONMENT: staging
    ANSIBLE_HOST_KEY_CHECKING: "false"
  script:
    - ( echo "cat <<EOF" ; cat docker-compose-tpl.yml ; echo EOF ) | sh > docker-compose.yml
    - ansible-playbook -i ./ansible/hosts/staging.yml -v ./ansible/deploy.yml
  only:
    - tags
    - dev
    - test
