#image: ${CI_IMAGE}

#before_script:
#  - cp -r /root/citools .

stages:
#  - build
#  - publish
  - deploy_staging

#build:
#  stage: build
#  tags:
#    - java
#  script: yarn install && yarn build
#  only:
#    - tags
#
#  artifacts:
#    paths:
#      - build/
#    expire_in: 60 mins
#    when: on_success
#
#publish:
#  stage: publish
#  tags:
#    - java
#  script:
#    - . ./citools/publish-image.sh
#  only:
#    - tags

deploy_staging:
  stage: deploy_staging
  image: ${DEPLOY_IMAGE}
  tags:
    - java
  script:
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - ansible-playbook -i ./ansible/hosts/staging.yml -v ./ansible/deploy-staging.yml
