image: ${CI_IMAGE}

stages:
  - build
  - publish
  - deploy_staging

build:
  stage: build
  retry: 2
  tags:
    - java
  script:
    - yarn config set registry http://192.168.10.123:8081/repository/taobao/
    - yarn install
    - yarn build
  only:
    - tags

  artifacts:
    paths:
      - build/
    expire_in: 60 mins
    when: on_success

publish:
  stage: publish
  retry: 2
  tags:
    - java
  script:
    - cp -r /root/citools .
    - . ./citools/publish-image.sh
  only:
    - tags

deploy_staging:
  stage: deploy_staging
  image: ${DEPLOY_IMAGE}
  retry: 2
  tags:
    - java
  dependencies: []
  script:
    - ( echo "cat <<EOF" ; cat docker-compose-tpl.yml ; echo EOF ) | sh > docker-compose.yml
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - ansible-playbook -i ./ansible/hosts/staging.yml -v ./ansible/deploy.yml
  only:
    - tags
