version: '3.8'
services:
  skill-editor-webapp:
    image: registry.cn-hangzhou.aliyuncs.com/zmsys/skill-editor-webapp:$CI_COMMIT_REF_NAME
    environment:
      NODE_ENV: production
      VERSION: $CI_COMMIT_REF_NAME
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.labels.kind == app
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 20s
        order: stop-first
        failure_action: rollback
      resources:
        limits:
          cpus: '1.0'
          memory: 1gb
      labels:
        traefik.enable: 'true'
        traefik.http.routers.skill-editor-webapp.rule: 'Host(\`editor-dev.aitekapp.com\`)'
        traefik.http.routers.skill-editor-webapp.tls: 'true'
        traefik.http.routers.skill-editor-webapp.tls.options: noClientAuth@file
        traefik.http.services.skill-editor-webapp.loadbalancer.server.port: 7443

        # traefik.http.services.skill-editor-webapp.loadbalancer.healthCheck.path: /health
        # traefik.http.services.skill-editor-webapp.loadbalancer.healthCheck.interval: 20s
        # traefik.http.services.skill-editor-webapp.loadbalancer.healthCheck.timeout: 15s


    ####################### logging config #################################
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
