import { schema } from 'relient/reducers';

export const user = new schema.Entity('user');
export const role = new schema.Entity('role');
export const resource = new schema.Entity('resource');
export const auditResourceType = new schema.Entity('auditResourceType', {}, { idAttribute: 'resourceType' });
export const skillPermission = new schema.Entity('skillPermission', {}, { idAttribute: 'userId' });
export const auditLog = new schema.Entity('auditLog');
export const product = new schema.Entity('product');
export const output = new schema.Entity('output');
export const intent = new schema.Entity('intent');
export const rule = new schema.Entity('rule');
export const builtinIntent = new schema.Entity('builtinIntent');
export const words = new schema.Entity('words');
export const productVersion = new schema.Entity('productVersion');
export const skillVersion = new schema.Entity('skillVersion');
export const intervention = new schema.Entity('intervention');
export const testCase = new schema.Entity('testCase');
export const testSuite = new schema.Entity('testSuite');
export const testJob = new schema.Entity('testJob');
export const testJobResult = new schema.Entity('testJobResult');
export const intentMap = new schema.Entity('intentMap');
export const intentMapInfo = new schema.Entity('intentMapInfo');
export const information = new schema.Entity('information');
export const skillAppInfo = new schema.Entity('skillAppInfo');
export const skillAppSentence = new schema.Entity('skillAppSentence');
